# Generated by Django 4.1.7 on 2024-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='document',
            field=models.FileField(default=None, upload_to='documents'),
        ),
    ]
