# Generated by Django 4.1.7 on 2024-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_requestservice_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='document',
            field=models.FileField(default=None, upload_to='document'),
        ),
    ]
