# Generated by Django 4.1.7 on 2024-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_requestservice_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
