# Generated by Django 4.1.7 on 2024-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_requestservice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='feedback',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='pending', max_length=200),
        ),
    ]
