# Generated by Django 4.1.7 on 2024-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_requestservice_feedback_requestservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='feedback',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
